"use strict";
const { EventEmitter } = require("node:events");
const { randomUUID, createHash } = require("node:crypto");

// Session-only, text-only utility. Never reads or migrates legacy disk history.
class ClipboardHistory extends EventEmitter {
  constructor(clipboard) {
    super();
    this.clipboard = clipboard;
    this.enabled = false;
    this.items = [];
    this.last = null;
    this.timer = null;
  }
  snapshot() { return { enabled: this.enabled, items: this.items.map((item) => ({ ...item })) }; }
  read() {
    const formats = this.clipboard.availableFormats();
    // Respect common password-manager/transient markers; not all apps mark secrets.
    if (formats.some((value) => /concealed|transient|autogenerated|password/i.test(value))) return null;
    const text = this.clipboard.readText();
    if (!text?.trim() || text.length > 20000) return null;
    return { text, hash: createHash("sha256").update(text).digest("hex") };
  }
  setEnabled(enabled) {
    if (enabled === this.enabled) return this.snapshot();
    if (this.timer) clearInterval(this.timer);
    this.timer = null;
    this.enabled = enabled;
    this.items = [];
    this.last = null;
    if (enabled) {
      // Do not retrospectively collect whatever was copied before consent.
      try { this.last = this.read()?.hash ?? null; } catch { /* unavailable clipboard */ }
      this.timer = setInterval(() => this.poll(), 700);
      this.timer.unref?.();
    }
    this.emit("change", this.snapshot());
    return this.snapshot();
  }
  poll() {
    if (!this.enabled) return;
    try {
      const value = this.read();
      if (!value) { this.last = null; return; }
      if (value.hash === this.last) return;
      this.last = value.hash;
      this.items = [{ id: randomUUID(), text: value.text, copiedAt: Date.now() },
        ...this.items.filter((item) => item.text !== value.text)].slice(0, 30);
      this.emit("change", this.snapshot());
    } catch { /* A temporary OS failure must not expose clipboard content in logs. */ }
  }
  clear() {
    this.items = [];
    this.emit("change", this.snapshot());
    return this.snapshot();
  }
  remove(id) {
    this.items = this.items.filter((item) => item.id !== id);
    this.emit("change", this.snapshot());
    return this.snapshot();
  }
  copy(id) {
    const item = this.enabled && this.items.find((item) => item.id === id);
    if (!item) throw Object.assign(new Error("This clipboard item is no longer available."), { code: "NOT_FOUND" });
    this.clipboard.writeText(item.text);
    this.last = createHash("sha256").update(item.text).digest("hex");
    return true;
  }
  close() { this.setEnabled(false); }
}
module.exports = { ClipboardHistory };
